pb: enable super && little cleanup
Co-authored-by: rokibhasansagar <rokibhasansagar2014@outlook.com>
Signed-off-by: Mohd Faraz <androiabledroid@gmail.com>

diff --git a/updater/update-binary b/updater/update-binary
--- a/updater/update-binary
+++ b/updater/update-binary
@@ -62,6 +62,7 @@ ui_print "|            Based on TWRP v3.4.0-x           |";
 ui_print "|---------------------------------------------|";
 PB=/tmp/pb/PBRP
 IMG=/tmp/pb/TWRP/recovery.img
+SUPER=$(find /dev/block/bootdevice/by-name/ | grep -q 'super')
 E=/etc/install-recovery.sh
 ETC=/s$E
 _ETC=/s/system$E
@@ -83,10 +84,10 @@ chmod 0755 /sbin/awk
 fi
 
 #AB Checking
-if [[ "$AB_DEVICE" = "false" ]]; then
+if [ "$AB_DEVICE" = "false" ] && [ "$SUPER" != "0" ]; then
 # Find Recovery Partition
  for PARTITION in system android_recovery ANDROID_RECOVERY RECOVERY recovery FOTAKernel ; do
-   if [[ "$PARTITION" = "system" ]]; then
+   if [ "$PARTITION" = "system" ] && [ "$SUPER" != "0" ]; then
      SYSTEM=$(readlink /dev/block/by-name/$PARTITION || readlink /dev/block/platform/*/by-name/$PARTITION || \
                readlink /dev/block/platform/*/*/by-name/$PARTITION || readlink /dev/$PARTITION);
    else
@@ -101,12 +102,14 @@ if [[ "$AB_DEVICE" = "false" ]]; then
  done;
 fi
 
-if [[ ! -z $SYSTEM ]]; then
-mkdir /s
-mount -t ext4 $SYSTEM /s
-else
-/sbin/mount /system && mount_sys="system"
-/sbin/mount /system_root && mount_sys="root"
+if [ "$SUPER" != "0" ]; then
+	if [ ! -z $SYSTEM ]; then
+		mkdir /s
+		mount -t ext4 $SYSTEM /s
+	else
+		/sbin/mount /system && mount_sys="system"
+		/sbin/mount /system_root && mount_sys="root"
+	fi
 fi
 
 if [[ "$RECOVERY" = "/dev/recovery" && "$AB_DEVICE" = "false" ]]; then
@@ -115,72 +118,62 @@ else
 	DD=false;
 fi
 
-#Deletion
-if [[ -f $ETC ]]; then
-rm $ETC
-fi
-if [[ -f ${_ETC} ]]; then
-rm ${_ETC}
-fi
-if [[ -f $PB1_PATH ]]; then
-rm -rf $PB1_PATH
-fi
-if [[ -f $PB2_PATH ]]; then
-rm -rf $PB2_PATH
-fi
-if [[ -f $PB3_PATH ]]; then
-rm -rf $PB3_PATH
-fi
-if [[ -f $UI ]]; then
-rm $UI
-fi
-if [[ -f $RES ]]; then
-rm -rf $RES
-fi
-if [[ -f $OLD ]]; then
-rm -rf $OLD
-fi
-if [[ "$mount_sys" = "system" ]]; then
-rm -rf /system$E;
-fi
-if [[ "$mount_sys" = "root" ]]; then
-rm -rf /system_root/system$E;
+if [ "$SUPER" != "0" ]; then
+	# Deletion
+	[ -f "$ETC" ] && rm "$ETC"
+	[ -f "${_ETC}" ] && rm "${_ETC}"
+	[ -f "$PB1_PATH" ] && rm -rf "$PB1_PATH"
+	[ -f "$PB2_PATH" ] && rm -rf "$PB2_PATH"
+	[ -f "$PB3_PATH" ] && rm -rf "$PB3_PATH"
+	[ -f "$UI" ] && rm "$UI"
+	[ -f "$RES" ] && rm -rf "$RES"
+	[ -f "$OLD" ] && rm -rf "$OLD"
+	[ "$mount_sys" = "system" ] && rm -rf /system$E
+	[ "$mount_sys" = "root" ] && rm -rf /system_root/system$E
 fi
 
 AB_D() {
- BOOT="/tmp/unpack-boot"
- REC="/tmp/unpack-rec"
- ui_print "Doing Work on slot $1"
- #Dump & unpack & Cp
- # dd if=/dev/block/bootdevice/by-name/$1 "of=/tmp/boot.img"
- mkdir $BOOT
- mkdir $REC
- dd if=/dev/block/bootdevice/by-name/$1 "of=/tmp/unpack-boot/boot.img"
- cd $BOOT
- "$tool" unpack -h boot.img
- # kernel string want_initramfs -> skip_initramfs (Magisk)
- $tool hexpatch kernel 77616E745F696E697472616D6673 736B69705F696E697472616D6673;
- # kernel string trip_initramfs -> skip_initramfs (SuperSU)
- $tool hexpatch kernel 747269705F696E697472616D6673 736B69705F696E697472616D6673;
- $tool cpio ramdisk.cpio test
- if [[ "$?" = "1" ]]; then
-   echo "$1=1" >> /tmp/pb/installed
- else
-   echo "$1=0" >> /tmp/pb/installed
- fi
- # boot.img header cmdline remove skip_override (flar2 patch)
- sed -i "s|$(grep '^cmdline=' header | cut -d= -f2-)|$(grep '^cmdline=' header | cut -d= -f2- | sed -e 's/skip_override//' -e 's/  */ /g' -e 's/[ \t]*$//')|" header;
- rm -rf ramdisk.cpio
- cd $REC
- "$tool" unpack $IMG
- cp ramdisk.cpio $BOOT/ramdisk.cpio
- cd $BOOT
- rm -rf $REC
- "$tool" repack boot.img
- dd if=new-boot.img of=/dev/block/bootdevice/by-name/$1
- [ $? = 0 ] && echo "installed=1" >> /tmp/pb/installed|| abort "Failed to flash $1 Image Please Restore the Boot.img"
- cd /tmp/pb
- rm -rf $BOOT
+	BOOT="/tmp/unpack-boot"
+	REC="/tmp/unpack-rec"
+	ui_print "Doing Work on slot $1"
+	if [ "$SUPER" != "0" ]; then
+		# Dump & unpack & Cp
+		mkdir "$BOOT" "$REC"
+		dd if=/dev/block/bootdevice/by-name/"$1" of=/tmp/unpack-boot/boot.img
+		cd "$BOOT" || exit
+		"$tool" unpack -h boot.img
+		# kernel string want_initramfs -> skip_initramfs (Magisk)
+		"$tool" hexpatch kernel 77616E745F696E697472616D6673 736B69705F696E697472616D6673;
+		# kernel string trip_initramfs -> skip_initramfs (SuperSU)
+		"$tool" hexpatch kernel 747269705F696E697472616D6673 736B69705F696E697472616D6673;
+		if "$tool" cpio ramdisk.cpio test; then
+			echo "$1=0" >> /tmp/pb/installed
+		else
+			echo "$1=1" >> /tmp/pb/installed
+		fi
+		# boot.img header cmdline remove skip_override (flar2 patch)
+		sed -i "s|$(grep '^cmdline=' header | cut -d= -f2-)|$(grep '^cmdline=' header | cut -d= -f2- | sed -e 's/skip_override//' -e 's/  */ /g' -e 's/[ \t]*$//')|" header;
+		rm -rf ramdisk.cpio
+		cd "$REC" || exit
+		"$tool" unpack "$IMG"
+		cp ramdisk.cpio "$BOOT"/ramdisk.cpio
+		cd "$BOOT" || exit
+		rm -rf "$REC"
+		"$tool" repack boot.img
+		if dd if=new-boot.img of=/dev/block/bootdevice/by-name/"$1"; then
+			echo "installed=1" >> /tmp/pb/installed
+		else
+			abort "Failed to flash $1 Image, Please Restore the Boot.img"
+		fi
+		cd /tmp/pb || exit
+		rm -rf "$BOOT"
+	else
+		if dd if=$IMG of=/dev/block/bootdevice/by-name/"$1"; then
+			echo "installed_$(echo $1 | cut -d'_' -f2)=1" >> /tmp/pb/installed
+		else
+			abort "Failed to flash $1 Image, Please Restore the Boot.img"
+		fi
+	fi
 }
 
 #Flashing
@@ -195,6 +188,9 @@ else
 		if [[ "$?" = "0" ]]; then
 			echo "installed=1" >> /tmp/pb/installed
 		fi
+	elif [ "$SUPER" == "0" ]; then
+		AB_D recovery_a
+		AB_D recovery_b
 	else
 		AB_D boot_a;
 		AB_D boot_b;
@@ -237,14 +233,12 @@ ui_print "|---------------------------------------------|";
 sleep 5s
 show_progress 0.1000000, 90 ;
 ui_print "|------------Installation finished!-----------|";
-if [[ -z "$SYSTEM" ]]; then
- if [[ "$mount_sys" = "system" ]]; then
-  /sbin/umount /system;
- fi
- if [[ "$mount_sys" = "root" ]]; then
-  /sbin/umount /system_root;
- fi
-else
-umount /s;
-rm -rf /s;
+if [ "$SUPER" != "0" ]; then
+	if [ -z "$SYSTEM" ]; then
+		[ "$mount_sys" = "system" ] && /sbin/umount /system
+		[ "$mount_sys" = "root" ] && /sbin/umount /system_root
+	else
+		umount /s
+		rm -rf /s
+	fi
 fi
