Flash Scripted Updated
 * Remove Bash Script
 * Added Inbuild Script Support by which
   Everything will be shown on flashing
   screen not in logs
 * Added Details

diff --git a/updater/update-binary b/updater/update-binary
--- a/updater/update-binary
+++ b/updater/update-binary
@@ -6,11 +6,12 @@ DIR=`dirname "$ZIP"`;
 
 ui_print() {
   until [ ! "$1" ]; do
-    echo -e "ui_print $1\nui_print" > $OUTFD;
+    echo -e "ui_print $1\nui_print" > $OUTFD ;
     shift;
   done;
 }
-show_progress() { echo "progress $1 $2" > $OUTFD; }
+
+show_progress() { echo "progress $1 $2" > /proc/self/fd/$2; }
 set_perm_recursive() {
   dirs=$(echo $* | awk '{ print substr($0, index($0,$5)) }');
   for i in $dirs; do
@@ -27,23 +28,126 @@ mkdir -p /tmp/pb;
 cd /tmp/pb;
 unzip -o "$ZIP";
 show_progress 0.1000000, 0;
-ui_print "|-------------------------------------------|";
-ui_print "|--------------PitchBlack TWRP--------------|";
-ui_print "|-------------------v2.6--------------------|";
-ui_print "|-----------For devicename----------|";
-ui_print "|-------------------------------------------|";
-ui_print "|           Based on TWRP v3.2.1-0          |";
-ui_print "|-------------------------------------------|";
+ui_print "|---------------------------------------------|";
+ui_print "|---------------PitchBlack TWRP---------------|";
+ui_print "|--------------------v2.6---------------------|";
+ui_print "|---------------------------------------------|";
+ui_print "|---------------------------------------------|";
+ui_print "|------------Developed By Reza Adi------------|";
+ui_print "|---------------------------------------------|";
+ui_print "|--------------Themed By FireWolf-------------|";
+ui_print "|---------------------------------------------|";
+ui_print "|---Maintained By Manjot Sidhu & Mohd Faraz---|";
+ui_print "|---------------------------------------------|";
+ui_print "|            Based on TWRP v3.2.1-0           |";
+ui_print "|---------------------------------------------|";
 /sbin/busybox mount /system;
-/sbin/sh /tmp/pb/flash_pb.sh;
-ui_print "|-------------------------------------------|";
-ui_print "|-------------------------------------------|";
-ui_print "|-------------------------------------------|";
-ui_print "|-------------------------------------------|";
-ui_print "|                 Thank You                 |";
-ui_print "|      Rebooting into PitchBlack TWRP       |";
-ui_print "|-------------------------------------------|";
+PB=/tmp/pb/PBTWRP
+IMG=/tmp/pb/TWRP/recovery.img
+ETC=/system/etc/install-recovery.sh
+PB1_PATH=/sdcard/Android/PBTWRP
+PB2_PATH=/sdcard/TWRP/PBTWRP
+UI=/sdcard/TWRP/theme/ui.zip
+RES=/sdcard/TWRP/.twrps
+red='\033[0;31m'
+
+recovery_partition() {
+	chk_syml() {
+		RECOVERY=$(readlink -f "$RECOVERY")
+		# symlink
+		if [ -f "$RECOVERY" ]; then
+			DD=true
+		elif [ -b "$RECOVERY" ]; then
+			case "$RECOVERY" in
+				/dev/block/bml*|/dev/block/mtd*|/dev/block/mmc*)
+					DD=false ;;
+				*)
+					DD=true ;;
+			esac
+		# otherwise we have to keep trying other locations
+		else
+			return 1
+		fi
+		ui_print "- Found recovery partition at: $RECOVERY"
+	}
+	# if we already have recovery block set then verify and use it
+	[ "$RECOVERY" ] && chk_syml && return
+	# otherwise, time to go hunting!
+	if [ -f /etc/recovery.fstab ]; then
+		# recovery fstab v1
+		RECOVERY=$(awk '$1 == "/recovery" {print $3}' /etc/recovery.fstab)
+		[ "$RECOVERY" ] && chk_syml && return
+		# recovery fstab v2
+		RECOVERY=$(awk '$2 == "/recovery" {print $1}' /etc/recovery.fstab)
+		[ "$RECOVERY" ] && chk_syml && return
+	fi
+	for fstab in /fstab.*; do
+		[ -f "$fstab" ] || continue
+		# device fstab v2
+		RECOVERY=$(awk '$2 == "/recovery" {print $1}' "$fstab")
+		[ "$RECOVERY" ] && chk_syml && return
+		# device fstab v1
+		RECOVERY=$(awk '$1 == "/recovery" {print $3}' "$fstab")
+		[ "$RECOVERY" ] && chk_syml && return
+	done
+	if [ -f /proc/emmc ]; then
+		# emmc layout
+		RECOVERY=$(awk '$4 == "\"recovery\"" {print $1}' /proc/emmc)
+		[ "$RECOVERY" ] && RECOVERY=/dev/block/$(echo "$RECOVERY" | cut -f1 -d:) && chk_syml && return
+	fi
+	if [ -f /proc/mtd ]; then
+		# mtd layout
+		RECOVERY=$(awk '$4 == "\"recovery\"" {print $1}' /proc/mtd)
+		[ "$RECOVERY" ] && RECOVERY=/dev/block/$(echo "$RECOVERY" | cut -f1 -d:) && chk_syml && return
+	fi
+	if [ -f /proc/dumchar_info ]; then
+		# mtk layout
+		RECOVERY=$(awk '$1 == "/recovery" {print $5}' /proc/dumchar_info)
+		[ "$RECOVERY" ] && chk_syml && return
+	fi
+	abort "$red Failed to Find RECOVERY Partition";
+	
+}
+
+#Deletion
+if [ -f $ETC ]; then
+	rm $ETC
+fi
+if [ -f $PB1_PATH ]; then
+	rm -rf $PB1_PATH
+fi
+if [ -f $PB2_PATH ]; then
+	rm -rf $PB2_PATH
+fi
+if [ -f $UI ]; then
+	rm $UI
+fi
+if [ -f $RES ]; then
+	rm -rf $RES
+fi
+
+#Flashing
+recovery_partition;
+if [ $? = 0 ]; then
+	if $DD; then
+		dd if=$IMG of="$RECOVERY"
+	else
+		flash_image $RECOVERY $IMG
+	fi
+	#Copy Specific Files
+	cp -r $PB/* /sdcard/TWRP/PBTWRP/
+else
+	abort "Failed to write recovery image!" 43;
+fi
+ui_print "|---------------------------------------------|";
+ui_print "|---------------------------------------------|";
+ui_print "|---------------------------------------------|";
+ui_print "|---------------------------------------------|";
+ui_print "|                  Thank You                  |";
+ui_print "|       Rebooting into PitchBlack TWRP        |";
+ui_print "|---------------------------------------------|";
 sleep 5s
 show_progress 0.1000000, 90 ;
+ui_print "|------------Installation finished!-----------|";
 /sbin/unmount /system;
 reboot recovery
