update binary: Try To fix 32bit MTK Flashing

diff --git a/updater/update-binary b/updater/update-binary
--- a/updater/update-binary
+++ b/updater/update-binary
@@ -50,6 +50,16 @@ PB2_PATH=/sdcard/TWRP/PBTWRP
 UI=/sdcard/TWRP/theme/ui.zip
 RES=/sdcard/TWRP/.twrps
 red='\033[0;31m'
+RECOVERY=/dev/recovery
+
+if [ -f "$(readlink -f "$RECOVERY")" ]; then
+	DD=true
+	break
+elif [[ ! -f "$(readlink -f "$RECOVERY")" ] || [ -f "$RECOVERY" ]]; then
+	DD=false
+	break
+else
+{
 
 recovery_partition() {
 	chk_syml() {
@@ -105,8 +115,10 @@ recovery_partition() {
 		RECOVERY=$(awk '$1 == "/recovery" {print $5}' /proc/dumchar_info)
 		[ "$RECOVERY" ] && chk_syml && return
 	fi
-	abort "$red Failed to Find RECOVERY Partition";
+	abort "Failed to Find RECOVERY Partition";
 	
+}
+fi
 }
 
 #Deletion
@@ -127,18 +139,28 @@ if [ -f $RES ]; then
 fi
 
 #Flashing
-recovery_partition;
-if [ $? = 0 ]; then
-	if $DD; then
+if [ "$DD" ]; then
+	if [ "$DD" == "true" ]; then
 		dd if=$IMG of="$RECOVERY"
 	else
 		flash_image $RECOVERY $IMG
 	fi
-	#Copy Specific Files
-	cp -r $PB/* /sdcard/TWRP/PBTWRP/
 else
-	abort "Failed to write recovery image!" 43;
+	recovery_partition;
+	if [ $? = 0 ]; then
+		if $DD; then
+			dd if=$IMG of="$RECOVERY"
+		else
+			flash_image $RECOVERY $IMG
+		fi
+	else
+		abort "Failed to write recovery image!" 43;
+	fi
 fi
+
+#Copy Specific Files
+cp -r $PB/* /sdcard/TWRP/PBTWRP/
+
 ui_print "|---------------------------------------------|";
 ui_print "|---------------------------------------------|";
 ui_print "|---------------------------------------------|";
